FROM gradle:8.5.0-jdk21-alpine AS build
COPY . /home/gradle/src
WORKDIR /home/gradle/src

ARG USERNAME
ARG TOKEN

RUN gradle :api:bootJar --no-daemon \
    -PgithubUsername=${USERNAME} \
    -PgithubToken=${TOKEN}

FROM eclipse-temurin:21-jre-alpine
EXPOSE 8080 5005

ENV SPRING_PROFILES_ACTIVE=default
ENV JAVA_OPTS=""

RUN mkdir /app
COPY --from=build /home/gradle/src/api/build/libs/*.jar /app/spring-boot-application.jar

ENTRYPOINT sh -c "java ${JAVA_OPTS} -jar -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} /app/spring-boot-application.jar"